server:
  port: 8081
  servlet:
    encoding:
      force-response: true
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 1234qwer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  token:
    key: hello
